# Generated by Django 6.0.6 on 2026-07-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('finished', models.DateField(verbose_name='date finished')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
